### ISSUE TITLE
Team list box not taking full width

### ISSUE THREAD

**Issue by areepp** [dotslashf/bagi-timnya#2]
Halo bang, saya yang dulu bilang pingin nyoba contribute project ini di discord wpu. Setelah liat2, saya nemu minor styling issue nih. Box anggota tim waktu viewportnya gede, nggak menuhin box parentnya.

![image](https://user-images.githubusercontent.com/90843952/221354614-6f85c4cb-c141-42fb-9bdd-b031f49a4d8c.png)

**Comment by dotslashf** [comment]
wah thank you banget @areepp, kemaren sempat nemu issue ini tapi belum sempat di fix 👏🔥
